### ISSUE TITLE
Business rules

### ISSUE THREAD

**Issue by gregpmillr** [gregpmillr/Advanced-Database#14]

**Comment by dpulsifer** [comment]
https://eduglopedia.org/resource/cea008e18dee42899aeff7a0c58dddaf8e9b5bc6/download

**Comment by dpulsifer** [comment]
Denormalized (Star Schema)

* An EMPLOYEE can make many ORDERS, but an ORDER can be made by one and only one EMPLOYEE.

* A CUSTOMER can place many ORDERS, but an ORDER can be placed by one and only one CUSTOMER.

* A PRODUCT can be purchased in many ORDERS, and an ORDER can purchase many products.

Normalized

* A CUSTOMER can place many ORDERS, but an ORDER can be placed by one and only one CUSTOMER.

* An EMPLOYEE can process many customer ORDERS, but a customer ORDER can be processed by one and only one EMPLOYEE.

* A REGION can have many EMPLOYEES, but an EMPLOYEE can only have one REGION.

* A CATEGORY can have many PRODUCTS, but a PRODUCT can only have one CATEGORY.

* An ORDER can generate a customer purchase for many products in ORDER DETAILS, but a product in ORDER DETAILS is generated by one and only one customer ORDER.

* A PRODUCT can be purchased many times in ORDER DETAILS, but an ORDER DETAIL is for one and only one PRODUCT.
